### ISSUE TITLE
ican get collection from web console, but i get it from appwrite_dart  trow '404' not found

### ISSUE THREAD

**Issue by TSCSOftware** [appwrite/sdk-for-dart#12]
### 👟 Reproduction steps

i upgrade appwrite server to  v:0.11.0.170  and edit my flutter app code.
then i test apps again.but app content isnt showed.
then i check code, i found appwrite error 
then check collection id and collection in web console .. there are fine.
 
then i user dart_Appwrite package to list documents it returns
`http://127.0.0.1:9100?uri=http://127.0.0.1:4901/b6H65rThbgs=/
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: AppwriteException: Collection not found (404)
#0      ClientIO.call (package:dart_appwrite/src/client_io.dart:117:9)
<asynchronous suspension>
#1      Test1.<anonymous closure> (package:testwin/test/1.dart:16:20)
<asynchronous suspension>`

i tride APpwrite pkg too
it return `Reloaded 34 of 1939 libraries in 3,010ms.
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: AppwriteException: Collection not found (404)
#0      ClientMixin.prepareResponse (package:appwrite/src/client_mixin.dart:76:9)
#1      ClientIO.call (package:appwrite/src/client_io.dart:242:19)
<asynchronous suspension>
#2      Database.listDocuments (package:appwrite/services/database.dart:39:17)
<asynchronous suspension>
#3      Test1.<anonymous closure> (package:testwin/test/1.dart:16:20)
<asynchronous suspension>`
then i try another functions...all are reruns null

### 👍 Expected behavior

i canged my server domain,openssl key

### 👎 Actual Behavior

i dont know

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Something else

### 🧱 Your Environment

windows 10
flutter 2.5.3
appwrite v:0.11.0.170
 flutter pkg
  dart_appwrite: ^1.0.2
  appwrite: ^2.0.3

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TSCSOftware** [comment]
@eldadfux @TorstenDittmann

**Comment by TSCSOftware** [comment]
i install appwrite to other serrver.but problem isnt sloved @eldadfux @TorstenDittmann

**Comment by wess** [comment]
Are you using the sdk in a flutter app or Dart (only) app?

**Comment by lohanidamodar** [comment]
@TSCSOftware  are you using the key with proper scope?

**Comment by lohanidamodar** [comment]
Closing as no new information has been received. If you are still having the issue feel free to reopen.
