### ISSUE TITLE
🐛 Bug Report: createFloatAttribute() 'AppwriteException: Invalid min: Value must be a valid float (400)'

### ISSUE THREAD

**Issue by sbergmair** [appwrite/sdk-for-dart#17]
### 👟 Reproduction steps

1. Create collection via interface in appwrite console and add an float attribute without min and max
2. Copy the json
3. Call `AttributeFloat.fromMap(json)` (Bug https://github.com/appwrite/sdk-for-dart/issues/16 needs to be fixed), but simple workaround is adding `xdefault: map['default']?.toDouble()` in `AttributeFloat.fromMap`
4. call `database.createFloatAttribute(collectionId: <the_collection_id>, key: attributeFloat.key, xrequired: attributeFloat.xrequired, min: attributeFloat.min.toString(), max: attributeFloat.max.toString(), xdefault: attributeFloat.xdefault.toString(), array: attributeFloat.array);`

### 👍 Expected behavior

Creating the correct attribute with min and max values

### 👎 Actual Behavior

AppwriteException: Invalid min: Value must be a valid float (400)
Attribute doesn't get created correctly

### 🎲 Appwrite version

Version 0.12.1.201 

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
Should be fixed on `dart_appwrite: 4.0.2`
