### ISSUE TITLE
Update is returning Collection instead of Database

### ISSUE THREAD

**Issue by pixeluvw** [appwrite/sdk-for-dart#23]
### 👟 Reproduction steps

Database.update();

### 👍 Expected behavior

It should return `models.Database.fromMap(res.data);`

### 👎 Actual Behavior

But it returns a collection
![Screenshot from 2022-07-28 18-27-21](https://user-images.githubusercontent.com/25572802/181589759-95883dc4-175a-44b9-bf09-edca8486aa6e.png)

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

no

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@stnguyen90 This should be fixed with latest update, please update accordingly.
