### ISSUE TITLE
🚀 Feature: Improve Pub Points on pub.dev

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/sdk-for-dart#29]
### 🔖 Feature description

pub.dev score: https://pub.dev/packages/dart_appwrite/score

1. [ ] Use an OSI-approved license. Sample projects with a valid [BSD-3](https://opensource.org/licenses/BSD-3-Clause) license
    * [url_launcher](https://github.com/flutter/plugins/blob/main/packages/url_launcher/url_launcher/LICENSE) 
    * [device_info_plus](https://github.com/fluttercommunity/plus_plugins/blob/main/packages/device_info_plus/device_info_plus/LICENSE)
    * [intl](https://github.com/dart-lang/intl/blob/master/LICENSE)
3. [ ] Code has no errors, warnings, lints, or formatting issues

### 🎤 Pitch

Packages with a higher pub points look better.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Perhaps the BSD-3 License isn't picked up because of our 3rd clause.

```diff
- 3. Neither the name Appwrite nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
+ 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
```

**Comment by stnguyen90** [comment]
I think this is the thing that checks for the license: https://github.com/dart-lang/pana

**Comment by lohanidamodar** [comment]
@stnguyen90 closing this as we now have Full score.
