### ISSUE TITLE
🐛 Bug Report: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>'

### ISSUE THREAD

**Issue by sibin-compatio** [appwrite/sdk-for-dart#33]
### 👟 Reproduction steps

$permissions: map['\$permissions'] modelling does work with appwrite version v:1.0.1.500

### 👍 Expected behavior

permission should be Map in Collection model

### 👎 Actual Behavior

"$permissions" is [_InternalLinkedHashMap] but in model is List

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@sibin-compatio thanks for raising this issue! 🙏🏼 I think this is a duplicate of https://github.com/appwrite/appwrite/issues/4543. In particular, please take a look at how you're creating the document as mentioned in https://github.com/appwrite/appwrite/issues/4543#issuecomment-1285911644. 

Would you be able to 👍🏼 that issue and close this issue?

**Comment by sibin-compatio** [comment]
@stnguyen90 My bad, Thanks for letting me know this.
