### ISSUE TITLE
📚 Documentation: Client.call supports ResponseType.bytes but how to respond from server?

### ISSUE THREAD

**Issue by kutoman** [appwrite/sdk-for-dart#37]
### 💭 Description

The sdk supports calls like `final respo = await client.call(HttpMethod.get, path: "myPath", responseType: ResponseType.bytes);` but I can't figure out how a dart cloud function can respond accordingly. This is not tackled in the docs. Furthermore how can we send requests with byte data payloads?

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
Hey,
The dart cloud function can't yet respond in file. Also the `call` method is internal to handle API calls and supports bytes response when viewing and downloading files.
 If you do want the cloud functions to respond with Files, please create relevant issue in https://github.com/open-runtimes/open-runtimes repository.

**Comment by kutoman** [comment]
@lohanidamodar thanks for the clarification
