### ISSUE TITLE
Question: How do I generate user session?

### ISSUE THREAD

**Issue by WilliamCunhaCardoso** [appwrite/sdk-for-dart#52]
I want to, when a given email and password, authenticate and generate session. I cannot find proper methods for it under Users and Account class. Can someone help me?

**Comment by lohanidamodar** [comment]
@WilliamCunhaCardoso You should use `Account` service for methods related to authentication. Also be advised, our `sdk-for-dart` is a server side SDK that is used in pair with `API_KEY`. If you are looking for client side SDK for Flutter please check https://github.com/appwrite/sdk-for-flutter
To learn more about `Account` service you can head over to docs at https://appwrite.io/docs/references/cloud/client-web/account
